### ISSUE TITLE
where should we host the context for `safechef` credential? 

### ISSUE THREAD

**Issue by JSAssassin** [credential-handler/vc-examples#12]
Currently the issuance and verification of safechef credential is failing in chapi playground with the following error - 

```
Unable to generate/issue credential: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```

That is because the response we get back from the `httpClient.get(url)` call in the document loader doesn't contain response data since gh pages doesn't add/support custom headers. So, we need to host the context somewhere else.

**Comment by davidlehn** [comment]
Can this be handled like other examples?  The alumni one uses https://playground.chapi.io/examples/alumni/alumni-v1.json.  Perhaps move that safechef context to the same repo and host it in a similar way?  A rename from .jsonld to .json might fix the content type issue.

An additional option would be to put in w3id.org URLs in the credentials and setup redirects there to the current hosting.

**Comment by JSAssassin** [comment]
> Can this be handled like other examples? The alumni one uses https://playground.chapi.io/examples/alumni/alumni-v1.json. Perhaps move that safechef context to the same repo and host it in a similar way? A rename from .jsonld to .json might fix the content type issue.

That was a good catch. https://playground.chapi.io is Chapi Playground.  The credentials were copied from there to the /vc-examples repo, though we removed `alumni-v1.json` and `ticket-v1.json` files  since @gannan08  said we don't want to 
host contexts in this repo and that they should be hosted elsewhere See [comment](https://github.com/credential-handler/vc-examples/pull/9#issuecomment-1466376861)- . So this means we should also host these two contexts wherever we'll be hosting the context for `safechef`.  

> An additional option would be to put in w3id.org URLs in the credentials and setup redirects there to the current hosting.
I am a +1 to this if others agree.

**Comment by dlongley** [comment]
@JSAssassin,

I think @gannan08's point was that we won't be hosting contexts for others in this repo. I believe that he did not, at the time, know that we had created the safe chef context and were the maintainers. If we're the maintainers of a particular context, it makes sense for us to host it -- the only question is where. We should put the safe chef context wherever the other example contexts we're hosting are today -- and whenever / wherever those move, the safe chef context would move along with them.

I don't think we want / need additional `w3id.org` URLs for these credentials because they are strictly examples -- at least today -- that we don't expect to be long-lived. If any of these credentials become more stable and we intend them to be more than examples, then that makes sense to do. Either way, that wouldn't address the problem of where to host the safe chef context today as `w3id.org` is just a redirection service ... it would just allow us to move its hosting location later without disrupting existing issued example VCs. However, I don't think that's enough of a concern right now to do something about.

If we do elect to add some extra `w3id.org` redirects -- we should just do it for a whole directory of VC example contexts that we can move around together in the future.

**Comment by JSAssassin** [comment]
> @JSAssassin,
> 
> I think @gannan08's point was that we won't be hosting contexts for others in this repo. I believe that he did not, at the time, know that we had created the safe chef context and were the maintainers. If we're the maintainers of a particular context, it makes sense for us to host it -- the only question is where. We should put the safe chef context wherever the other example contexts we're hosting are today -- and whenever / wherever those move, the safe chef context would move along with them.
> Got it. The other contexts(movie ticket and alumni) were being hosted by chapi playground so, I've added them back in this repo. I've also added the context for `safechef` in here and updated the context URLs.  https://github.com/credential-handler/vc-examples/pull/13

**Comment by JSAssassin** [comment]
Closing, example contexts are hosted inside `vc-examples` and  are served by `vc-playground-contexts-server`.
